name: decloy CD

on:
  push:
    branches: ['AWS-EC2']
  pull_request:
    branches: ['AWS-EC2']

jobs:
  build:
    runs-on: ubuntu-20.0
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: create env file
        working-directory: ./backend
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-
      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./blog-vanilla.zip s3://blog-vanilla-bucket/public
      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name blog-vanilla-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name deploy-group
          --s3-location bucket=blog-vanilla-bucket,bundleType=zip,key=public/blog-vanilla.zip
